### ISSUE TITLE
Don't know whether I'm sending a post card or not

### ISSUE THREAD

**Issue by aliar97** [placeholder-team-name/placeholder#21]
When I click preview and then send, there is no notification for me to know if I actually sent it or not. Also if I have a blank message and I press send there's no error or success message showing. This is definitely a major issue.

**Comment by kwokwilliam** [comment]
We were unable to replicate this issue. This is the second issue we have regarding this, so we will look into it more.

**Comment by kwokwilliam** [comment]
We have been continually unable to replicate this issue.

**Comment by clairehjk** [comment]
This issue is not replicable but we have changed it to redirect to a new page after sending.  https://github.com/placeholder-team-name/postcards/pull/35

**Comment by vincentmvdm** [comment]
Just to clarify for Andy and Selene:

Even though we have since made a UX improvement to how this works, we do not believe this issue existed in the first place. Reasoning from yesterday's Slack message:

"We have “sent” feedback for both filled out postcards and empty postcards: https://www.dropbox.com/s/kzsq7gewkvcbooh/Screen%20Shot%202019-06-11%20at%204.46.33%20PM.png?dl=0 (this is after sending an empty postcard)"
